// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using S5_01_App_CS_GOAT.Models.EntityFramework;

#nullable disable

namespace S5_01_App_CS_GOAT.Migrations
{
    [DbContext(typeof(CSGOATDbContext))]
    [Migration("20251212082732_UserValidation")]
    partial class UserValidation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Ban", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id");

                    b.Property<int>("BanTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("bnt_id");

                    b.Property<DateTime>("BanDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ban_bandate");

                    b.Property<int>("BanDuration")
                        .HasColumnType("integer")
                        .HasColumnName("ban_banduration");

                    b.Property<int>("BanId")
                        .HasColumnType("integer")
                        .HasColumnName("ban_id");

                    b.Property<string>("BanReason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ban_reason");

                    b.HasKey("UserId", "BanTypeId");

                    b.HasIndex("BanDate");

                    b.HasIndex("BanTypeId");

                    b.ToTable("t_j_ban_ban");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.BanType", b =>
                {
                    b.Property<int>("BanTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bnt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BanTypeId"));

                    b.Property<string>("BanTypeDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bnt_bantypedescription");

                    b.Property<string>("BanTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bnt_bantypename");

                    b.Property<int?>("ParentBanTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("bnt_parentid");

                    b.HasKey("BanTypeId");

                    b.HasIndex("BanTypeName")
                        .IsUnique();

                    b.HasIndex("ParentBanTypeId");

                    b.ToTable("t_e_bantype_bnt");

                    b.HasData(
                        new
                        {
                            BanTypeId = 1,
                            BanTypeDescription = "Perte d'accès à tous les fonctions du site, connexion incluse.",
                            BanTypeName = "Total"
                        },
                        new
                        {
                            BanTypeId = 2,
                            BanTypeDescription = "Compte en lecture seule.",
                            BanTypeName = "Transactionnel",
                            ParentBanTypeId = 1
                        },
                        new
                        {
                            BanTypeId = 3,
                            BanTypeDescription = "Impossibilité de modifier l'inventaire.",
                            BanTypeName = "Inventaire",
                            ParentBanTypeId = 2
                        },
                        new
                        {
                            BanTypeId = 4,
                            BanTypeDescription = "Interdiction d'ouvrir des caisses.",
                            BanTypeName = "Ouverture",
                            ParentBanTypeId = 3
                        },
                        new
                        {
                            BanTypeId = 5,
                            BanTypeDescription = "Restrictions sur les ventes d'objets.",
                            BanTypeName = "Vente",
                            ParentBanTypeId = 3
                        },
                        new
                        {
                            BanTypeId = 6,
                            BanTypeDescription = "Les objets dans l'inventaire ne peuvent pas être améliorés.",
                            BanTypeName = "Amélioration",
                            ParentBanTypeId = 3
                        },
                        new
                        {
                            BanTypeId = 7,
                            BanTypeDescription = "Ne peut pas effectuer de dépôt ou de retrait.",
                            BanTypeName = "Monétaire",
                            ParentBanTypeId = 2
                        },
                        new
                        {
                            BanTypeId = 8,
                            BanTypeDescription = "Le compte ne peut pas être crédité depuis l'extérieur.",
                            BanTypeName = "Crédit",
                            ParentBanTypeId = 7
                        },
                        new
                        {
                            BanTypeId = 9,
                            BanTypeDescription = "Le solde ne peut pas être exporté vers d'autres plateformes.",
                            BanTypeName = "Débit",
                            ParentBanTypeId = 7
                        });
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Case", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cas_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CaseId"));

                    b.Property<string>("CaseImage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cas_caseimage");

                    b.Property<string>("CaseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cas_casename");

                    b.Property<double>("CasePrice")
                        .HasColumnType("double precision")
                        .HasColumnName("cas_caseprice");

                    b.HasKey("CaseId");

                    b.HasIndex("CaseName")
                        .IsUnique();

                    b.HasIndex("CasePrice");

                    b.ToTable("t_e_case_cas");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.CaseContent", b =>
                {
                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("cas_id")
                        .HasColumnOrder(1);

                    b.Property<int>("SkinId")
                        .HasColumnType("integer")
                        .HasColumnName("skn_id")
                        .HasColumnOrder(2);

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("cct_weight");

                    b.HasKey("CaseId", "SkinId");

                    b.HasIndex("SkinId");

                    b.HasIndex("Weight");

                    b.ToTable("t_j_casecontent_cct");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.FairRandom", b =>
                {
                    b.Property<int>("FairRandomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("frn_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FairRandomId"));

                    b.Property<string>("CombinedHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("frn_combinedhash");

                    b.Property<double?>("Fraction")
                        .HasColumnType("double precision")
                        .HasColumnName("frn_fraction");

                    b.Property<string>("ServerHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("frn_serverhash");

                    b.Property<string>("ServerSeed")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("frn_serverseed");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id");

                    b.Property<int?>("UserNonce")
                        .HasColumnType("integer")
                        .HasColumnName("frn_usernonce");

                    b.Property<string>("UserSeed")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("usr_seed");

                    b.HasKey("FairRandomId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("t_e_fairrandom_frn");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Favorite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id")
                        .HasColumnOrder(1);

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("cas_id")
                        .HasColumnOrder(2);

                    b.HasKey("UserId", "CaseId");

                    b.HasIndex("CaseId");

                    b.ToTable("t_j_favorite_fav");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.InventoryItem", b =>
                {
                    b.Property<int>("InventoryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("inv_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryItemId"));

                    b.Property<DateTime>("AcquiredOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("inv_acquiredon");

                    b.Property<float>("Float")
                        .HasColumnType("real")
                        .HasColumnName("inv_float");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("inv_isfavorite");

                    b.Property<DateTime?>("RemovedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("inv_removedon");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id");

                    b.Property<int>("WearId")
                        .HasColumnType("integer")
                        .HasColumnName("wer_id");

                    b.HasKey("InventoryItemId");

                    b.HasIndex("AcquiredOn");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("RemovedOn");

                    b.HasIndex("UserId");

                    b.HasIndex("WearId");

                    b.ToTable("t_j_inventoryitem_inv");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("itm_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<int?>("DefIndex")
                        .HasColumnType("integer")
                        .HasColumnName("itm_defindex");

                    b.Property<string>("ItemModel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("itm_itemmodel");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("itm_itemname");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("itt_id");

                    b.HasKey("ItemId");

                    b.HasIndex("DefIndex");

                    b.HasIndex("ItemName");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("t_e_item_itm");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.ItemType", b =>
                {
                    b.Property<int>("ItemTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("itt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemTypeId"));

                    b.Property<string>("ItemTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("itt_itemtypename");

                    b.Property<int?>("ParentItemTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("itt_parentid");

                    b.HasKey("ItemTypeId");

                    b.HasIndex("ItemTypeName")
                        .IsUnique();

                    b.HasIndex("ParentItemTypeId");

                    b.ToTable("t_e_itemtype_itt");

                    b.HasData(
                        new
                        {
                            ItemTypeId = 1,
                            ItemTypeName = "Pistol"
                        },
                        new
                        {
                            ItemTypeId = 2,
                            ItemTypeName = "Rifle"
                        },
                        new
                        {
                            ItemTypeId = 3,
                            ItemTypeName = "Sniper Rifle"
                        },
                        new
                        {
                            ItemTypeId = 4,
                            ItemTypeName = "Machinegun"
                        },
                        new
                        {
                            ItemTypeId = 5,
                            ItemTypeName = "SMG"
                        },
                        new
                        {
                            ItemTypeId = 6,
                            ItemTypeName = "Shotgun"
                        },
                        new
                        {
                            ItemTypeId = 7,
                            ItemTypeName = "Knife"
                        },
                        new
                        {
                            ItemTypeId = 8,
                            ItemTypeName = "Gloves"
                        });
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Limit", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id");

                    b.Property<int>("LimitTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("lmt_id");

                    b.Property<double?>("LimitAmount")
                        .HasColumnType("double precision")
                        .HasColumnName("lim_limitamount");

                    b.HasKey("UserId", "LimitTypeId");

                    b.HasIndex("LimitTypeId");

                    b.ToTable("t_j_limit_lim");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.LimitType", b =>
                {
                    b.Property<int>("LimitTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lmt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LimitTypeId"));

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("lmt_duration");

                    b.Property<string>("LimitTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lmt_limittypename");

                    b.HasKey("LimitTypeId");

                    b.HasIndex("LimitTypeName")
                        .IsUnique();

                    b.ToTable("t_e_limittype_lmt");

                    b.HasData(
                        new
                        {
                            LimitTypeId = 1,
                            Duration = 1,
                            LimitTypeName = "Dépôt Horaire"
                        },
                        new
                        {
                            LimitTypeId = 2,
                            Duration = 1,
                            LimitTypeName = "Dépenses Horaire"
                        },
                        new
                        {
                            LimitTypeId = 3,
                            Duration = 1,
                            LimitTypeName = "Ouvertures Horaire"
                        },
                        new
                        {
                            LimitTypeId = 4,
                            Duration = 1,
                            LimitTypeName = "Améliorations Horaire"
                        },
                        new
                        {
                            LimitTypeId = 5,
                            Duration = 24,
                            LimitTypeName = "Dépôt Quotidien"
                        },
                        new
                        {
                            LimitTypeId = 6,
                            Duration = 24,
                            LimitTypeName = "Dépenses Quotidien"
                        },
                        new
                        {
                            LimitTypeId = 7,
                            Duration = 24,
                            LimitTypeName = "Ouvertures Quotidien"
                        },
                        new
                        {
                            LimitTypeId = 8,
                            Duration = 24,
                            LimitTypeName = "Améliorations Quotidien"
                        },
                        new
                        {
                            LimitTypeId = 9,
                            Duration = 168,
                            LimitTypeName = "Dépôt Hebdomadaire"
                        },
                        new
                        {
                            LimitTypeId = 10,
                            Duration = 168,
                            LimitTypeName = "Dépenses Hebdomadaire"
                        },
                        new
                        {
                            LimitTypeId = 11,
                            Duration = 168,
                            LimitTypeName = "Ouvertures Hebdomadaire"
                        },
                        new
                        {
                            LimitTypeId = 12,
                            Duration = 168,
                            LimitTypeName = "Améliorations Hebdomadaire"
                        },
                        new
                        {
                            LimitTypeId = 13,
                            Duration = 720,
                            LimitTypeName = "Dépôt Mensuel"
                        },
                        new
                        {
                            LimitTypeId = 14,
                            Duration = 720,
                            LimitTypeName = "Dépenses Mensuel"
                        },
                        new
                        {
                            LimitTypeId = 15,
                            Duration = 720,
                            LimitTypeName = "Ouvertures Mensuel"
                        },
                        new
                        {
                            LimitTypeId = 16,
                            Duration = 720,
                            LimitTypeName = "Améliorations Mensuel"
                        });
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ntf_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("NotificationContent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ntf_notificationcontent");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ntf_notificationdate");

                    b.Property<string>("NotificationSummary")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ntf_notificationsummary");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("ntt_id");

                    b.HasKey("NotificationId");

                    b.HasIndex("NotificationDate");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("t_e_notification_ntf");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.NotificationSetting", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id")
                        .HasColumnOrder(1);

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("ntt_id")
                        .HasColumnOrder(2);

                    b.Property<bool>("ByEmail")
                        .HasColumnType("boolean")
                        .HasColumnName("nts_byemail");

                    b.Property<bool>("ByPhone")
                        .HasColumnType("boolean")
                        .HasColumnName("nts_byphone");

                    b.Property<bool>("OnSite")
                        .HasColumnType("boolean")
                        .HasColumnName("nts_onsite");

                    b.HasKey("UserId", "NotificationTypeId");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("t_j_notificationsetting_nts");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.NotificationType", b =>
                {
                    b.Property<int>("NotificationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ntt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationTypeId"));

                    b.Property<string>("NotificationTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ntt_notificationtypename");

                    b.HasKey("NotificationTypeId");

                    b.HasIndex("NotificationTypeName")
                        .IsUnique();

                    b.ToTable("t_e_notificationtype_ntt");

                    b.HasData(
                        new
                        {
                            NotificationTypeId = 1,
                            NotificationTypeName = "Annonce"
                        },
                        new
                        {
                            NotificationTypeId = 2,
                            NotificationTypeName = "Sécurité & Confidentialité"
                        },
                        new
                        {
                            NotificationTypeId = 3,
                            NotificationTypeName = "Offres Spéciales"
                        },
                        new
                        {
                            NotificationTypeId = 4,
                            NotificationTypeName = "Mise à jour"
                        },
                        new
                        {
                            NotificationTypeId = 5,
                            NotificationTypeName = "Évènement"
                        });
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pmt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentMethodId"));

                    b.Property<bool>("FromWallet")
                        .HasColumnType("boolean")
                        .HasColumnName("pmt_fromwallet");

                    b.Property<string>("PaymentMethodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pmt_paymentmethodname");

                    b.Property<bool>("ToWallet")
                        .HasColumnType("boolean")
                        .HasColumnName("pmt_towallet");

                    b.HasKey("PaymentMethodId");

                    b.HasIndex("PaymentMethodName")
                        .IsUnique();

                    b.ToTable("t_e_paymentmethod_pmt");

                    b.HasData(
                        new
                        {
                            PaymentMethodId = 1,
                            FromWallet = false,
                            PaymentMethodName = "Carte de crédit",
                            ToWallet = true
                        },
                        new
                        {
                            PaymentMethodId = 2,
                            FromWallet = true,
                            PaymentMethodName = "RIB",
                            ToWallet = false
                        },
                        new
                        {
                            PaymentMethodId = 3,
                            FromWallet = true,
                            PaymentMethodName = "PayPal",
                            ToWallet = true
                        });
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.PriceHistory", b =>
                {
                    b.Property<int>("PriceHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("prh_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PriceHistoryId"));

                    b.Property<DateTime?>("GuessDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("prh_guessdate");

                    b.Property<DateTime>("PriceDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("prh_pricedate");

                    b.Property<double>("PriceValue")
                        .HasColumnType("double precision")
                        .HasColumnName("prh_pricevalue");

                    b.Property<int>("SkinId")
                        .HasColumnType("integer")
                        .HasColumnName("skn_id");

                    b.Property<int>("WearTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("wrt_id");

                    b.HasKey("PriceHistoryId");

                    b.HasIndex("PriceDate");

                    b.HasIndex("SkinId");

                    b.HasIndex("WearTypeId");

                    b.ToTable("t_e_pricehistory_prh");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.PromoCode", b =>
                {
                    b.Property<int>("PromoCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("prc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PromoCodeId"));

                    b.Property<int?>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("cas_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prc_code");

                    b.Property<double?>("DiscountAmount")
                        .IsRequired()
                        .HasColumnType("double precision")
                        .HasColumnName("prc_discountamount");

                    b.Property<int?>("DiscountPercentage")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("prc_discountpercentage");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("prc_expirydate");

                    b.Property<TimeSpan?>("RefreshDelay")
                        .HasColumnType("interval")
                        .HasColumnName("prc_refreshdelay");

                    b.Property<int?>("RemainingUses")
                        .HasColumnType("integer")
                        .HasColumnName("prc_remaininguses");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id");

                    b.Property<DateTime?>("ValidityStart")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("prc_validitystart");

                    b.HasKey("PromoCodeId");

                    b.HasIndex("CaseId");

                    b.HasIndex("Code");

                    b.HasIndex("ExpiryDate");

                    b.HasIndex("UserId");

                    b.ToTable("t_e_promocode_prc");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Rarity", b =>
                {
                    b.Property<int>("RarityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rar_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RarityId"));

                    b.Property<string>("RarityColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rar_raritycolor");

                    b.Property<string>("RarityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rar_rarityname");

                    b.HasKey("RarityId");

                    b.HasIndex("RarityName")
                        .IsUnique();

                    b.ToTable("t_e_rarity_rar");

                    b.HasData(
                        new
                        {
                            RarityId = 1,
                            RarityColor = "#afafaf",
                            RarityName = "Consumer"
                        },
                        new
                        {
                            RarityId = 2,
                            RarityColor = "#6496e1",
                            RarityName = "Industrial"
                        },
                        new
                        {
                            RarityId = 3,
                            RarityColor = "#4b69cd",
                            RarityName = "Mil-Spec"
                        },
                        new
                        {
                            RarityId = 4,
                            RarityColor = "#8847ff",
                            RarityName = "Restricted"
                        },
                        new
                        {
                            RarityId = 5,
                            RarityColor = "#d32ce6",
                            RarityName = "Classified"
                        },
                        new
                        {
                            RarityId = 6,
                            RarityColor = "#eb4b4b",
                            RarityName = "Covert"
                        },
                        new
                        {
                            RarityId = 7,
                            RarityColor = "#f29b1d",
                            RarityName = "Contraband"
                        });
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Skin", b =>
                {
                    b.Property<int>("SkinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("skn_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SkinId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("itm_id");

                    b.Property<int>("PaintIndex")
                        .HasColumnType("integer")
                        .HasColumnName("skn_paintindex");

                    b.Property<int>("RarityId")
                        .HasColumnType("integer")
                        .HasColumnName("rar_id");

                    b.Property<string>("SkinName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("skn_skinname");

                    b.Property<int>("UvType")
                        .HasColumnType("integer")
                        .HasColumnName("skn_uvtype");

                    b.HasKey("SkinId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PaintIndex");

                    b.HasIndex("RarityId");

                    b.HasIndex("SkinName");

                    b.ToTable("t_e_skin_skn");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Token", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tkn_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("TokenCreationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("tkn_tokencreationdate");

                    b.Property<DateTime>("TokenExpiry")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("tkn_tokenexpiry");

                    b.Property<int>("TokenTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("tkt_id");

                    b.Property<string>("TokenValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tkn_token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id");

                    b.HasKey("TokenId");

                    b.HasIndex("TokenCreationDate");

                    b.HasIndex("TokenExpiry");

                    b.HasIndex("TokenTypeId");

                    b.HasIndex("TokenValue");

                    b.HasIndex("UserId");

                    b.ToTable("t_e_token_tkn");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.TokenType", b =>
                {
                    b.Property<int>("TokenTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tkt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenTypeId"));

                    b.Property<string>("TokenTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tkt_tokentypename");

                    b.HasKey("TokenTypeId");

                    b.HasIndex("TokenTypeName")
                        .IsUnique();

                    b.ToTable("t_e_tokentype_tkt");

                    b.HasData(
                        new
                        {
                            TokenTypeId = 1,
                            TokenTypeName = "Remember Cookie"
                        },
                        new
                        {
                            TokenTypeId = 2,
                            TokenTypeName = "Password Reset"
                        },
                        new
                        {
                            TokenTypeId = 3,
                            TokenTypeName = "Email Verification"
                        },
                        new
                        {
                            TokenTypeId = 4,
                            TokenTypeName = "Phone Verification"
                        },
                        new
                        {
                            TokenTypeId = 5,
                            TokenTypeName = "2FA"
                        });
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("txn_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<DateTime?>("CancelledOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("txn_cancelledon");

                    b.Property<int?>("NotificationId")
                        .HasColumnType("integer")
                        .HasColumnName("ntf_id");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("txn_transactiondate");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id");

                    b.Property<double>("WalletValue")
                        .HasColumnType("double precision")
                        .HasColumnName("txn_walletvalue");

                    b.HasKey("TransactionId");

                    b.HasIndex("CancelledOn");

                    b.HasIndex("NotificationId");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("UserId");

                    b.ToTable("t_e_transaction_txn");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.UpgradeResult", b =>
                {
                    b.Property<int>("InventoryItemId")
                        .HasColumnType("integer")
                        .HasColumnName("inv_id");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("tra_id");

                    b.Property<string>("DegradeFunction")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("upg_degradefuction");

                    b.Property<int>("FairRandomId")
                        .HasColumnType("integer")
                        .HasColumnName("frn_id");

                    b.Property<float>("FloatEnd")
                        .HasColumnType("real")
                        .HasColumnName("upg_floatend");

                    b.Property<float>("FloatStart")
                        .HasColumnType("real")
                        .HasColumnName("upg_floatstart");

                    b.Property<double>("ProbDegrade")
                        .HasColumnType("double precision")
                        .HasColumnName("upg_probdegrade");

                    b.Property<double>("ProbIntact")
                        .HasColumnType("double precision")
                        .HasColumnName("upg_probintact");

                    b.Property<double>("PropDestroy")
                        .HasColumnType("double precision")
                        .HasColumnName("upg_propdestroy");

                    b.HasKey("InventoryItemId", "TransactionId");

                    b.HasIndex("FairRandomId")
                        .IsUnique();

                    b.HasIndex("TransactionId");

                    b.ToTable("t_j_upgraderesult_upg");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usr_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("usr_creationdate");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("usr_deletedon");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("usr_displayname");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usr_email");

                    b.Property<DateTime?>("EmailVerifiedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("usr_emailverifiedon");

                    b.Property<string>("HashPassword")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usr_hashpassword");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("usr_isadmin");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("usr_lastlogin");

                    b.Property<string>("Login")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("usr_login");

                    b.Property<int>("Nonce")
                        .HasColumnType("integer")
                        .HasColumnName("usr_nonce");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("usr_phone");

                    b.Property<DateTime?>("PhoneVerifiedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("usr_phoneverifiedon");

                    b.Property<string>("SaltPassword")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usr_saltpassword");

                    b.Property<string>("Seed")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("usr_seed");

                    b.Property<string>("SteamId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usr_steamid");

                    b.Property<bool>("TwoFaIsEmail")
                        .HasColumnType("boolean")
                        .HasColumnName("usr_twofaisemail");

                    b.Property<bool>("TwoFaIsPhone")
                        .HasColumnType("boolean")
                        .HasColumnName("usr_twofaisphone");

                    b.Property<double>("Wallet")
                        .HasColumnType("double precision")
                        .HasColumnName("usr_wallet");

                    b.HasKey("UserId");

                    b.HasIndex("DeletedOn");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsAdmin");

                    b.HasIndex("LastLogin");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("SteamId")
                        .IsUnique();

                    b.ToTable("t_e_user_usr");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Wear", b =>
                {
                    b.Property<int>("WearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("wer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WearId"));

                    b.Property<int>("SkinId")
                        .HasColumnType("integer")
                        .HasColumnName("skn_id");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("wer_uuid");

                    b.Property<float>("WearFloat")
                        .HasColumnType("real")
                        .HasColumnName("wer_wearfloat");

                    b.Property<int>("WearTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("wrt_id");

                    b.HasKey("WearId");

                    b.HasIndex("SkinId");

                    b.HasIndex("Uuid");

                    b.HasIndex("WearTypeId");

                    b.ToTable("t_e_wear_wer");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.WearType", b =>
                {
                    b.Property<int>("WearTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("wrt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WearTypeId"));

                    b.Property<string>("WearTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("wrt_weartypename");

                    b.HasKey("WearTypeId");

                    b.HasIndex("WearTypeName")
                        .IsUnique();

                    b.ToTable("t_e_weartype_wrt");

                    b.HasData(
                        new
                        {
                            WearTypeId = 1,
                            WearTypeName = "Factory New"
                        },
                        new
                        {
                            WearTypeId = 2,
                            WearTypeName = "Minimal Wear"
                        },
                        new
                        {
                            WearTypeId = 3,
                            WearTypeName = "Field-Tested"
                        },
                        new
                        {
                            WearTypeId = 4,
                            WearTypeName = "Well-Worn"
                        },
                        new
                        {
                            WearTypeId = 5,
                            WearTypeName = "Battle-Scarred"
                        });
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.GlobalNotification", b =>
                {
                    b.HasBaseType("S5_01_App_CS_GOAT.Models.EntityFramework.Notification");

                    b.Property<bool>("IncludeVisitors")
                        .HasColumnType("boolean")
                        .HasColumnName("gnf_includevisitors");

                    b.HasIndex("IncludeVisitors");

                    b.ToTable("t_e_globalnotification_gnf", (string)null);
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.UserNotification", b =>
                {
                    b.HasBaseType("S5_01_App_CS_GOAT.Models.EntityFramework.Notification");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("unf_isread");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id");

                    b.HasIndex("UserId");

                    b.ToTable("t_e_usernotification_unf", (string)null);
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.ItemTransaction", b =>
                {
                    b.HasBaseType("S5_01_App_CS_GOAT.Models.EntityFramework.Transaction");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("integer")
                        .HasColumnName("inv_id");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("t_e_itemtransaction_itr");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.MoneyTransaction", b =>
                {
                    b.HasBaseType("S5_01_App_CS_GOAT.Models.EntityFramework.Transaction");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer")
                        .HasColumnName("pmt_id");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("t_e_moneytransaction_mtr");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.RandomTransaction", b =>
                {
                    b.HasBaseType("S5_01_App_CS_GOAT.Models.EntityFramework.ItemTransaction");

                    b.Property<int?>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("cas_id");

                    b.Property<int>("FairRandomId")
                        .HasColumnType("integer")
                        .HasColumnName("frn_id");

                    b.HasIndex("CaseId");

                    b.HasIndex("FairRandomId")
                        .IsUnique();

                    b.ToTable("t_e_randomtransaction_rtr");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Ban", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.BanType", "BanType")
                        .WithMany("Bans")
                        .HasForeignKey("BanTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_ban_bantype");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.User", "User")
                        .WithMany("Bans")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ban_user");

                    b.Navigation("BanType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.BanType", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.BanType", "ParentBanType")
                        .WithMany("SubBanTypes")
                        .HasForeignKey("ParentBanTypeId");

                    b.Navigation("ParentBanType");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.CaseContent", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Case", "Case")
                        .WithMany("CaseContents")
                        .HasForeignKey("CaseId")
                        .IsRequired()
                        .HasConstraintName("FK_casecontent_case");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Skin", "Skin")
                        .WithMany("CaseContents")
                        .HasForeignKey("SkinId")
                        .IsRequired()
                        .HasConstraintName("FK_casecontent_skin");

                    b.Navigation("Case");

                    b.Navigation("Skin");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.FairRandom", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.User", "User")
                        .WithOne("FairRandom")
                        .HasForeignKey("S5_01_App_CS_GOAT.Models.EntityFramework.FairRandom", "UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_fairrandom_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Favorite", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Case", "Case")
                        .WithMany("Favorites")
                        .HasForeignKey("CaseId")
                        .IsRequired()
                        .HasConstraintName("FK_favorite_case");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_favorite_user");

                    b.Navigation("Case");

                    b.Navigation("User");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.InventoryItem", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.User", "User")
                        .WithMany("InventoryItems")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_inventoryitem_user");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Wear", "Wear")
                        .WithMany("InventoryItems")
                        .HasForeignKey("WearId")
                        .IsRequired()
                        .HasConstraintName("FK_inventoryitem_wear");

                    b.Navigation("User");

                    b.Navigation("Wear");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Item", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.ItemType", "ItemType")
                        .WithMany("Items")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.ItemType", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.ItemType", "ParentItemType")
                        .WithMany("SubItemTypes")
                        .HasForeignKey("ParentItemTypeId");

                    b.Navigation("ParentItemType");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Limit", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.LimitType", "LimitType")
                        .WithMany("Limits")
                        .HasForeignKey("LimitTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_limit_limittype");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.User", "User")
                        .WithMany("Limits")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_limit_user");

                    b.Navigation("LimitType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Notification", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.NotificationType", "NotificationType")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_notification_notificationtype");

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.NotificationSetting", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.NotificationType", "NotificationType")
                        .WithMany("NotificationSettings")
                        .HasForeignKey("NotificationTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_notificationsetting_notificationtype");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.User", "User")
                        .WithMany("NotificationSettings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.PriceHistory", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Skin", "Skin")
                        .WithMany("PriceHistories")
                        .HasForeignKey("SkinId")
                        .IsRequired()
                        .HasConstraintName("FK_pricehistory_skin");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.WearType", "WearType")
                        .WithMany("PriceHistories")
                        .HasForeignKey("WearTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_pricehistory_weartype");

                    b.Navigation("Skin");

                    b.Navigation("WearType");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.PromoCode", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Case", "Case")
                        .WithMany("PromoCodes")
                        .HasForeignKey("CaseId")
                        .HasConstraintName("FK_promocode_case");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.User", "User")
                        .WithMany("PromoCodes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_promocode_user");

                    b.Navigation("Case");

                    b.Navigation("User");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Skin", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Item", "Item")
                        .WithMany("Skins")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK_skin_item");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Rarity", "Rarity")
                        .WithMany("Skins")
                        .HasForeignKey("RarityId")
                        .IsRequired()
                        .HasConstraintName("FK_skin_rarity");

                    b.Navigation("Item");

                    b.Navigation("Rarity");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Token", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.TokenType", "TokenType")
                        .WithMany("Tokens")
                        .HasForeignKey("TokenTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_token_tokentype");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_token_user");

                    b.Navigation("TokenType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Transaction", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Notification", "Notification")
                        .WithMany("Transactions")
                        .HasForeignKey("NotificationId");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_transaction_user");

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.UpgradeResult", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.FairRandom", "FairRandom")
                        .WithOne("UpgradeResult")
                        .HasForeignKey("S5_01_App_CS_GOAT.Models.EntityFramework.UpgradeResult", "FairRandomId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_fairrandom_upgraderesult");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.InventoryItem", "InventoryItem")
                        .WithMany("UpgradeResults")
                        .HasForeignKey("InventoryItemId")
                        .IsRequired()
                        .HasConstraintName("FK_upgraderesult_inventoryitem");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.RandomTransaction", "RandomTransaction")
                        .WithMany("UpgradeResults")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_upgraderesult_randomtransaction");

                    b.Navigation("FairRandom");

                    b.Navigation("InventoryItem");

                    b.Navigation("RandomTransaction");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Wear", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Skin", "Skin")
                        .WithMany("Wears")
                        .HasForeignKey("SkinId")
                        .IsRequired()
                        .HasConstraintName("FK_wear_skin");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.WearType", "WearType")
                        .WithMany("Wears")
                        .HasForeignKey("WearTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_wear_weartype");

                    b.Navigation("Skin");

                    b.Navigation("WearType");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.GlobalNotification", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Notification", null)
                        .WithOne()
                        .HasForeignKey("S5_01_App_CS_GOAT.Models.EntityFramework.GlobalNotification", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.UserNotification", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Notification", null)
                        .WithOne()
                        .HasForeignKey("S5_01_App_CS_GOAT.Models.EntityFramework.UserNotification", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_usernotification_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.ItemTransaction", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.InventoryItem", "InventoryItem")
                        .WithMany("ItemTransactions")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_itemtransaction_inventoryitem");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Transaction", null)
                        .WithOne()
                        .HasForeignKey("S5_01_App_CS_GOAT.Models.EntityFramework.ItemTransaction", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.MoneyTransaction", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.PaymentMethod", "PaymentMethod")
                        .WithMany("MoneyTransactions")
                        .HasForeignKey("PaymentMethodId")
                        .IsRequired()
                        .HasConstraintName("FK_moneytransaction_paymentmethod");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Transaction", null)
                        .WithOne()
                        .HasForeignKey("S5_01_App_CS_GOAT.Models.EntityFramework.MoneyTransaction", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.RandomTransaction", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Case", "Case")
                        .WithMany("RandomTransactions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_randomtransaction_case");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.FairRandom", "FairRandom")
                        .WithOne("RandomTransaction")
                        .HasForeignKey("S5_01_App_CS_GOAT.Models.EntityFramework.RandomTransaction", "FairRandomId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_fairrandom_randomtransaction");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.ItemTransaction", null)
                        .WithOne()
                        .HasForeignKey("S5_01_App_CS_GOAT.Models.EntityFramework.RandomTransaction", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("FairRandom");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.BanType", b =>
                {
                    b.Navigation("Bans");

                    b.Navigation("SubBanTypes");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Case", b =>
                {
                    b.Navigation("CaseContents");

                    b.Navigation("Favorites");

                    b.Navigation("PromoCodes");

                    b.Navigation("RandomTransactions");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.FairRandom", b =>
                {
                    b.Navigation("RandomTransaction");

                    b.Navigation("UpgradeResult");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.InventoryItem", b =>
                {
                    b.Navigation("ItemTransactions");

                    b.Navigation("UpgradeResults");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Item", b =>
                {
                    b.Navigation("Skins");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.ItemType", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("SubItemTypes");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.LimitType", b =>
                {
                    b.Navigation("Limits");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Notification", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.NotificationType", b =>
                {
                    b.Navigation("NotificationSettings");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.PaymentMethod", b =>
                {
                    b.Navigation("MoneyTransactions");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Rarity", b =>
                {
                    b.Navigation("Skins");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Skin", b =>
                {
                    b.Navigation("CaseContents");

                    b.Navigation("PriceHistories");

                    b.Navigation("Wears");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.TokenType", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.User", b =>
                {
                    b.Navigation("Bans");

                    b.Navigation("FairRandom");

                    b.Navigation("Favorites");

                    b.Navigation("InventoryItems");

                    b.Navigation("Limits");

                    b.Navigation("NotificationSettings");

                    b.Navigation("PromoCodes");

                    b.Navigation("Tokens");

                    b.Navigation("Transactions");

                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Wear", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.WearType", b =>
                {
                    b.Navigation("PriceHistories");

                    b.Navigation("Wears");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.RandomTransaction", b =>
                {
                    b.Navigation("UpgradeResults");
                });
#pragma warning restore 612, 618
        }
    }
}
