// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using S5_01_App_CS_GOAT.Models.EntityFramework;

#nullable disable

namespace S5_01_App_CS_GOAT.Migrations
{
    [DbContext(typeof(CSGOATDbContext))]
    partial class CSGOATDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Ban", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id")
                        .HasColumnOrder(1);

                    b.Property<int>("BanTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("bnt_id")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("BanDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ban_bandate");

                    b.Property<int>("BanDuration")
                        .HasColumnType("integer")
                        .HasColumnName("ban_banduration");

                    b.HasKey("UserId", "BanTypeId");

                    b.HasIndex("BanTypeId");

                    b.ToTable("t_j_ban_ban");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.BanType", b =>
                {
                    b.Property<int>("BanTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bnt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BanTypeId"));

                    b.Property<string>("BanTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bnt_bantypename");

                    b.HasKey("BanTypeId");

                    b.ToTable("t_e_bantype_bnt");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Case", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cas_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CaseId"));

                    b.Property<string>("CaseImage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cas_caseimage");

                    b.Property<string>("CaseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cas_casename");

                    b.Property<double>("CasePrice")
                        .HasColumnType("double precision")
                        .HasColumnName("cas_caseprice");

                    b.HasKey("CaseId");

                    b.ToTable("t_e_case_cas");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.CaseContent", b =>
                {
                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("cas_id")
                        .HasColumnOrder(1);

                    b.Property<int>("SkinId")
                        .HasColumnType("integer")
                        .HasColumnName("skn_id")
                        .HasColumnOrder(2);

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("cct_weight");

                    b.HasKey("CaseId", "SkinId");

                    b.HasIndex("SkinId");

                    b.ToTable("t_j_casecontent_cct");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.FairRandom", b =>
                {
                    b.Property<int>("FairRandomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("frn_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FairRandomId"));

                    b.Property<string>("CombinedHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("frn_combinedhash");

                    b.Property<double>("Fraction")
                        .HasColumnType("double precision")
                        .HasColumnName("frn_fraction");

                    b.Property<int?>("RandomTransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("rtr_id");

                    b.Property<string>("ServerHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("frn_serverhash");

                    b.Property<string>("ServerSeed")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("frn_serverseed");

                    b.Property<int?>("UserIdUpgrade")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id_upgrade");

                    b.Property<int>("UserNonce")
                        .HasColumnType("integer")
                        .HasColumnName("frn_usernonce");

                    b.Property<int?>("WearIdUpgrade")
                        .HasColumnType("integer")
                        .HasColumnName("wer_id_upgrade");

                    b.HasKey("FairRandomId");

                    b.HasIndex("RandomTransactionId");

                    b.HasIndex("UserIdUpgrade", "WearIdUpgrade");

                    b.ToTable("t_e_fairrandom_frn");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Favorite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id")
                        .HasColumnOrder(1);

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("cas_id")
                        .HasColumnOrder(2);

                    b.HasKey("UserId", "CaseId");

                    b.HasIndex("CaseId");

                    b.ToTable("t_j_favorite_fav");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.InventoryItem", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id")
                        .HasColumnOrder(1);

                    b.Property<int>("WearId")
                        .HasColumnType("integer")
                        .HasColumnName("wer_id")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("AcquiredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inv_acquiredon");

                    b.Property<float>("Float")
                        .HasColumnType("real")
                        .HasColumnName("inv_float");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("inv_isfavorite");

                    b.Property<DateTime?>("RemovedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inv_removedon");

                    b.HasKey("UserId", "WearId");

                    b.HasIndex("WearId");

                    b.ToTable("t_j_inventoryitem_inv");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("itm_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<int?>("DefIndex")
                        .HasColumnType("integer")
                        .HasColumnName("itm_defindex");

                    b.Property<string>("ItemModel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("itm_itemmodel");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("itm_itemname");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("itt_id");

                    b.HasKey("ItemId");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("t_e_item_itm");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.ItemType", b =>
                {
                    b.Property<int>("ItemTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("itt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemTypeId"));

                    b.Property<string>("ItemTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("itt_itemtypename");

                    b.Property<int?>("ParentItemTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("itt_parentid");

                    b.HasKey("ItemTypeId");

                    b.HasIndex("ParentItemTypeId");

                    b.ToTable("t_e_itemtype_itt");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Limit", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id");

                    b.Property<int>("LimitTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("lmt_id");

                    b.Property<double>("LimitAmount")
                        .HasColumnType("double precision")
                        .HasColumnName("lim_limitamount");

                    b.HasKey("UserId", "LimitTypeId");

                    b.HasIndex("LimitTypeId");

                    b.ToTable("t_j_limit_lim");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.LimitType", b =>
                {
                    b.Property<int>("LimitTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lmt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LimitTypeId"));

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("lmt_duration");

                    b.Property<string>("DurationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lmt_durationname");

                    b.Property<string>("LimitTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lmt_limittypename");

                    b.HasKey("LimitTypeId");

                    b.ToTable("t_e_limittype_lmt");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ntf_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("NotificationContent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ntf_notificationcontent");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ntf_notificationdate");

                    b.Property<string>("NotificationSummary")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ntf_notificationsummary");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("ntt_id");

                    b.HasKey("NotificationId");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("t_e_notification_ntf");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.NotificationSetting", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id")
                        .HasColumnOrder(1);

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("ntt_id")
                        .HasColumnOrder(2);

                    b.Property<bool>("ByEmail")
                        .HasColumnType("boolean")
                        .HasColumnName("nts_byemail");

                    b.Property<bool>("ByPhone")
                        .HasColumnType("boolean")
                        .HasColumnName("nts_byphone");

                    b.Property<bool>("OnSite")
                        .HasColumnType("boolean")
                        .HasColumnName("nts_onsite");

                    b.HasKey("UserId", "NotificationTypeId");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("t_j_notificationsetting_nts");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.NotificationType", b =>
                {
                    b.Property<int>("NotificationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ntt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationTypeId"));

                    b.Property<string>("NotificationTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ntt_notificationtypename");

                    b.HasKey("NotificationTypeId");

                    b.ToTable("t_e_notificationtype_ntt");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pmt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentMethodId"));

                    b.Property<bool>("FromWallet")
                        .HasColumnType("boolean")
                        .HasColumnName("pmt_fromwallet");

                    b.Property<string>("PaymentMethodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pmt_paymentmethodname");

                    b.Property<bool>("ToWallet")
                        .HasColumnType("boolean")
                        .HasColumnName("pmt_towallet");

                    b.HasKey("PaymentMethodId");

                    b.ToTable("t_e_paymentmethod_pmt");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.PriceHistory", b =>
                {
                    b.Property<int>("PriceHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("prc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PriceHistoryId"));

                    b.Property<DateTime?>("GuessDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prc_guessdate");

                    b.Property<DateTime>("PriceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prc_pricedate");

                    b.Property<double>("PriceValue")
                        .HasColumnType("double precision")
                        .HasColumnName("prc_pricevalue");

                    b.Property<int>("WearId")
                        .HasColumnType("integer")
                        .HasColumnName("wer_id");

                    b.HasKey("PriceHistoryId");

                    b.HasIndex("WearId");

                    b.ToTable("t_e_pricehistory_prc");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Rarity", b =>
                {
                    b.Property<int>("RarityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rar_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RarityId"));

                    b.Property<string>("RarityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rar_rarityname");

                    b.HasKey("RarityId");

                    b.ToTable("t_e_rarity_rar");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Skin", b =>
                {
                    b.Property<int>("SkinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("skn_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SkinId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("itm_id");

                    b.Property<int>("PaintIndex")
                        .HasColumnType("integer")
                        .HasColumnName("skn_paintindex");

                    b.Property<int>("RarityId")
                        .HasColumnType("integer")
                        .HasColumnName("rar_id");

                    b.Property<string>("SkinName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("skn_skinname");

                    b.HasKey("SkinId");

                    b.HasIndex("ItemId");

                    b.HasIndex("RarityId");

                    b.ToTable("t_e_skin_skn");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Token", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tkn_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("TokenCreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tkn_tokencreationdate");

                    b.Property<DateTime>("TokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tkn_tokenexpiry");

                    b.Property<int>("TokenTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("tkt_id");

                    b.Property<string>("TokenValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tkn_token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id");

                    b.HasKey("TokenId");

                    b.HasIndex("TokenTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("t_e_token_tkn");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.TokenType", b =>
                {
                    b.Property<int>("TokenTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tkt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenTypeId"));

                    b.Property<string>("TokenTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tkt_tokentypename");

                    b.HasKey("TokenTypeId");

                    b.ToTable("t_e_tokentype_tkt");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("txn_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<DateTime?>("CancelledOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("txn_cancelledon");

                    b.Property<int?>("NotificationId")
                        .HasColumnType("integer")
                        .HasColumnName("ntf_id");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("txn_transactiondate");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id");

                    b.Property<double>("WalletValue")
                        .HasColumnType("double precision")
                        .HasColumnName("txn_walletvalue");

                    b.HasKey("TransactionId");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("t_e_transaction_txn");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.UpgradeResult", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id")
                        .HasColumnOrder(1);

                    b.Property<int>("WearId")
                        .HasColumnType("integer")
                        .HasColumnName("wer_id")
                        .HasColumnOrder(2);

                    b.Property<string>("DegradeFunction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("upg_degradefuction");

                    b.Property<float>("FloatEnd")
                        .HasColumnType("real")
                        .HasColumnName("upg_floatend");

                    b.Property<float>("FloatStart")
                        .HasColumnType("real")
                        .HasColumnName("upg_floatstart");

                    b.Property<double>("ProbDegrade")
                        .HasColumnType("double precision")
                        .HasColumnName("upg_probdegrade");

                    b.Property<double>("ProbIntact")
                        .HasColumnType("double precision")
                        .HasColumnName("upg_probintact");

                    b.Property<double>("PropDestroy")
                        .HasColumnType("double precision")
                        .HasColumnName("upg_propdestroy");

                    b.HasKey("UserId", "WearId");

                    b.ToTable("t_j_upgraderesult_upg");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usr_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usr_creationdate");

                    b.Property<DateTime?>("DeleteOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usr_deletedon");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usr_displayname");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usr_email");

                    b.Property<DateTime?>("EmailVerifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usr_emailverifiedon");

                    b.Property<string>("HashPassword")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usr_hashpassword");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("usr_isadmin");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usr_lastlogin");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usr_login");

                    b.Property<int>("Nonce")
                        .HasColumnType("integer")
                        .HasColumnName("usr_nonce");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("usr_phone");

                    b.Property<DateTime?>("PhoneVerifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usr_phoneverifiedon");

                    b.Property<string>("SaltPassword")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usr_saltpassword");

                    b.Property<string>("Seed")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("usr_seed");

                    b.Property<string>("SteamId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usr_steamid");

                    b.Property<bool>("TwoFaIsEmail")
                        .HasColumnType("boolean")
                        .HasColumnName("usr_twofaisemail");

                    b.Property<bool>("TwoFaIsPhone")
                        .HasColumnType("boolean")
                        .HasColumnName("usr_twofaisphone");

                    b.Property<double>("Wallet")
                        .HasColumnType("double precision")
                        .HasColumnName("usr_wallet");

                    b.HasKey("UserId");

                    b.ToTable("t_e_user_usr");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Wear", b =>
                {
                    b.Property<int>("WearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("wer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WearId"));

                    b.Property<float>("FloatHigh")
                        .HasColumnType("real")
                        .HasColumnName("wer_floathigh");

                    b.Property<float>("FloatLow")
                        .HasColumnType("real")
                        .HasColumnName("wer_floatlow");

                    b.Property<int>("SkinId")
                        .HasColumnType("integer")
                        .HasColumnName("skn_id");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("wer_uuid");

                    b.Property<int>("WearValue")
                        .HasColumnType("integer")
                        .HasColumnName("wer_wearid");

                    b.HasKey("WearId");

                    b.HasIndex("SkinId");

                    b.ToTable("t_e_wear_wer");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.GlobalNotification", b =>
                {
                    b.HasBaseType("S5_01_App_CS_GOAT.Models.EntityFramework.Notification");

                    b.Property<bool>("IncludeVisitors")
                        .HasColumnType("boolean")
                        .HasColumnName("gnf_includevisitors");

                    b.ToTable("t_e_globalnotification_gnf", (string)null);
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.UserNotification", b =>
                {
                    b.HasBaseType("S5_01_App_CS_GOAT.Models.EntityFramework.Notification");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id");

                    b.HasIndex("UserId");

                    b.ToTable("t_e_usernotification_unf", (string)null);
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.ItemTransaction", b =>
                {
                    b.HasBaseType("S5_01_App_CS_GOAT.Models.EntityFramework.Transaction");

                    b.Property<int?>("UserIdItem")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id_item");

                    b.Property<int?>("WearIdItem")
                        .HasColumnType("integer")
                        .HasColumnName("wer_id");

                    b.HasIndex("UserIdItem", "WearIdItem");

                    b.ToTable("t_e_itemtransaction_itr");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.MoneyTransaction", b =>
                {
                    b.HasBaseType("S5_01_App_CS_GOAT.Models.EntityFramework.Transaction");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer")
                        .HasColumnName("pmt_id");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("t_e_moneytransaction_mtr");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.RandomTransaction", b =>
                {
                    b.HasBaseType("S5_01_App_CS_GOAT.Models.EntityFramework.Transaction");

                    b.Property<int?>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("cas_id");

                    b.Property<int?>("UserIdUpgrade")
                        .HasColumnType("integer")
                        .HasColumnName("usr_id_upgrade");

                    b.Property<string>("UserSeed")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("rtr_userseed");

                    b.Property<int?>("WearIdUpgrade")
                        .HasColumnType("integer")
                        .HasColumnName("wer_id_upgrade");

                    b.HasIndex("CaseId");

                    b.HasIndex("UserIdUpgrade", "WearIdUpgrade");

                    b.ToTable("t_e_randomtransaction_rtr");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Ban", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.BanType", "BanType")
                        .WithMany("Bans")
                        .HasForeignKey("BanTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_ban_bantype");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.User", "User")
                        .WithMany("Bans")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ban_user");

                    b.Navigation("BanType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.CaseContent", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Case", "Case")
                        .WithMany("CaseContents")
                        .HasForeignKey("CaseId")
                        .IsRequired()
                        .HasConstraintName("FK_casecontent_case");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Skin", "Skin")
                        .WithMany("CaseContents")
                        .HasForeignKey("SkinId")
                        .IsRequired()
                        .HasConstraintName("FK_casecontent_skin");

                    b.Navigation("Case");

                    b.Navigation("Skin");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.FairRandom", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.RandomTransaction", "RandomTransaction")
                        .WithMany("FairRandoms")
                        .HasForeignKey("RandomTransactionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_fairrandom_randomtransaction");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.UpgradeResult", "UpgradeResult")
                        .WithMany("FairRandoms")
                        .HasForeignKey("UserIdUpgrade", "WearIdUpgrade")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_fairrandom_upgraderesult");

                    b.Navigation("RandomTransaction");

                    b.Navigation("UpgradeResult");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Favorite", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Case", "Case")
                        .WithMany("Favorites")
                        .HasForeignKey("CaseId")
                        .IsRequired()
                        .HasConstraintName("FK_favorite_case");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_favorite_user");

                    b.Navigation("Case");

                    b.Navigation("User");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.InventoryItem", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.User", "User")
                        .WithMany("InventoryItems")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_inventoryitem_user");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Wear", "Wear")
                        .WithMany("InventoryItems")
                        .HasForeignKey("WearId")
                        .IsRequired()
                        .HasConstraintName("FK_inventoryitem_wear");

                    b.Navigation("User");

                    b.Navigation("Wear");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Item", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.ItemType", "ItemType")
                        .WithMany("Items")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.ItemType", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.ItemType", "ParentItemType")
                        .WithMany("SubItemTypes")
                        .HasForeignKey("ParentItemTypeId");

                    b.Navigation("ParentItemType");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Limit", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.LimitType", "LimitType")
                        .WithMany("Limits")
                        .HasForeignKey("LimitTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_limit_limittype");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.User", "User")
                        .WithMany("Limits")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_limit_user");

                    b.Navigation("LimitType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Notification", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.NotificationType", "NotificationType")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_notification_notificationtype");

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.NotificationSetting", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.NotificationType", "NotificationType")
                        .WithMany("NotificationSettings")
                        .HasForeignKey("NotificationTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_notificationsetting_notificationtype");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.User", "User")
                        .WithMany("NotificationSettings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.PriceHistory", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Wear", "Wear")
                        .WithMany("PriceHistories")
                        .HasForeignKey("WearId")
                        .IsRequired()
                        .HasConstraintName("FK_pricehistory_wear");

                    b.Navigation("Wear");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Skin", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Item", "Item")
                        .WithMany("Skins")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK_skin_item");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Rarity", "Rarity")
                        .WithMany("Skins")
                        .HasForeignKey("RarityId")
                        .IsRequired()
                        .HasConstraintName("FK_skin_rarity");

                    b.Navigation("Item");

                    b.Navigation("Rarity");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Token", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.TokenType", "TokenType")
                        .WithMany("Tokens")
                        .HasForeignKey("TokenTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_token_tokentype");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_token_user");

                    b.Navigation("TokenType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Transaction", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Notification", "Notification")
                        .WithMany("Transactions")
                        .HasForeignKey("NotificationId");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_transaction_user");

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.UpgradeResult", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.InventoryItem", "InventoryItem")
                        .WithMany("UpgradeResults")
                        .HasForeignKey("UserId", "WearId")
                        .IsRequired()
                        .HasConstraintName("FK_upgraderesult_inventoryitem");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Wear", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Skin", "Skin")
                        .WithMany("Wears")
                        .HasForeignKey("SkinId")
                        .IsRequired()
                        .HasConstraintName("FK_wear_skin");

                    b.Navigation("Skin");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.GlobalNotification", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Notification", null)
                        .WithOne()
                        .HasForeignKey("S5_01_App_CS_GOAT.Models.EntityFramework.GlobalNotification", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.UserNotification", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Notification", null)
                        .WithOne()
                        .HasForeignKey("S5_01_App_CS_GOAT.Models.EntityFramework.UserNotification", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_usernotification_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.ItemTransaction", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Transaction", null)
                        .WithOne()
                        .HasForeignKey("S5_01_App_CS_GOAT.Models.EntityFramework.ItemTransaction", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.InventoryItem", "InventoryItem")
                        .WithMany("ItemTransactions")
                        .HasForeignKey("UserIdItem", "WearIdItem")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_itemtransaction_inventoryitem");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.MoneyTransaction", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.PaymentMethod", "PaymentMethod")
                        .WithMany("MoneyTransactions")
                        .HasForeignKey("PaymentMethodId")
                        .IsRequired()
                        .HasConstraintName("FK_moneytransaction_paymentmethod");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Transaction", null)
                        .WithOne()
                        .HasForeignKey("S5_01_App_CS_GOAT.Models.EntityFramework.MoneyTransaction", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.RandomTransaction", b =>
                {
                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Case", "Case")
                        .WithMany("RandomTransactions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_randomtransaction_case");

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.Transaction", null)
                        .WithOne()
                        .HasForeignKey("S5_01_App_CS_GOAT.Models.EntityFramework.RandomTransaction", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("S5_01_App_CS_GOAT.Models.EntityFramework.UpgradeResult", "UpgradeResult")
                        .WithMany("RandomTransactions")
                        .HasForeignKey("UserIdUpgrade", "WearIdUpgrade")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_randomtransaction_upgraderesult");

                    b.Navigation("Case");

                    b.Navigation("UpgradeResult");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.BanType", b =>
                {
                    b.Navigation("Bans");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Case", b =>
                {
                    b.Navigation("CaseContents");

                    b.Navigation("Favorites");

                    b.Navigation("RandomTransactions");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.InventoryItem", b =>
                {
                    b.Navigation("ItemTransactions");

                    b.Navigation("UpgradeResults");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Item", b =>
                {
                    b.Navigation("Skins");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.ItemType", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("SubItemTypes");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.LimitType", b =>
                {
                    b.Navigation("Limits");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Notification", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.NotificationType", b =>
                {
                    b.Navigation("NotificationSettings");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.PaymentMethod", b =>
                {
                    b.Navigation("MoneyTransactions");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Rarity", b =>
                {
                    b.Navigation("Skins");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Skin", b =>
                {
                    b.Navigation("CaseContents");

                    b.Navigation("Wears");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.TokenType", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.UpgradeResult", b =>
                {
                    b.Navigation("FairRandoms");

                    b.Navigation("RandomTransactions");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.User", b =>
                {
                    b.Navigation("Bans");

                    b.Navigation("Favorites");

                    b.Navigation("InventoryItems");

                    b.Navigation("Limits");

                    b.Navigation("NotificationSettings");

                    b.Navigation("Tokens");

                    b.Navigation("Transactions");

                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.Wear", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("PriceHistories");
                });

            modelBuilder.Entity("S5_01_App_CS_GOAT.Models.EntityFramework.RandomTransaction", b =>
                {
                    b.Navigation("FairRandoms");
                });
#pragma warning restore 612, 618
        }
    }
}
